In [0]:
import numpy as np

In [0]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexing

In [0]:
arr8=arr1.copy()
arr8[:,[0,3]]=arr8[:,[3,0]]
arr8

array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])

In [0]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row

In [0]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
arr1[[0,3]]=arr1[[3,0]]
arr1

array([[15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [0]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [0]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2

In [0]:
res=np.where(np.isnan(arr2),np.ma.array(arr2,mask=np.isnan(arr2)).mean(axis=0),arr2)

In [0]:
res

array([[1. , 2. , 7.5],
       [4. , 5. , 6. ],
       [2.5, 3.5, 9. ]])

In [0]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[77, 43, 28, 63],
       [62,  8, 98, 61],
       [94, 57, 82, 12],
       [83,  6, 40, 16],
       [78,  2, 51, 10]])

In [0]:
# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3

In [0]:
result=arr3[(arr3>25)|(arr3 %3==0)]

In [0]:
result

array([77, 43, 28, 63, 62, 98, 61, 94, 57, 82, 12, 83,  6, 40, 78, 51])

In [0]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile()

In [0]:
print("arr :", arr3)
print("10th percentile of arr:",
      np.percentile(arr3,10))
print("25th percentile of arr:",
      np.percentile(arr3,25))
print("50th percentile of arr:",
      np.percentile(arr3,50))

arr : [[77 43 28 63]
 [62  8 98 61]
 [94 57 82 12]
 [83  6 40 16]
 [78  2 51 10]]
10th percentile of arr: 7.800000000000001
25th percentile of arr: 15.0
50th percentile of arr: 54.0
